- name: varaiables
  hosts: local
  connection: local
  vars :
   COURSE: Devops with AWS
   DURATION: 120 Hrs
   Trainer : Siva Kumar Reddy
  tasks : 
    - name: print the varaiables
      ansible.builtin.debug:
       msg: "{{COUSRE}} , {{DURATION}} , {{Trainer}} "