- name: install packages
  hosts: [172.31.30.123 ]
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - gcc
    - mysql
    - git
    - zip
       