- name : configure backend server
  hosts: backend
  become : yes
  tasks : 
    - name : disable node js
      ansible.builtin.command: dnf module disable nodejs -y
    
    - name : enable node js 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name : install nodejs
      ansible.builtin.package:
        - name : nodejs
          state : present

